// expected compile error

func invalid_call(in : s32) s32
{
    return in;
}


func main() s32
{
    return invalid_call();
}